---
- name: To change {{user_name}} password
  hosts: all
  remote_user : ansadmin
  become : true
  gather_facts: false
  vars:
    user_name: samurai
  vars_prompt:
    - name: new_password
      prompt: "Enter new password for {{user_name}}"
      encrypt: "md5_crypt"
      confirm: yes
  tasks:
    - name: Changing {{user_name}} Password
      user:
        name: "{{ user_name }}"
        update_password: always
        password: "{{ new_password }}"
        state: present
